name: check_lint
on:
  push:
  pull_request:

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Check formatting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python for test py3.11
        uses: actions/setup-python@v4
        with:
          python-version: py3.11
      - name: Install tox
        run: python -m pip install '.[test]'
      - name: Run test suite
        run: tox -e lint
